version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_greenpath
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: greenpath
      MYSQL_USER: greenpath_user      # Opcional: crear un usuario específico
      MYSQL_PASSWORD: greenpath_pass  # Opcional: contraseña para el usuario
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql    # Volumen persistente para datos
      - ./greenpath_dump.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

  web:
    build: .
    container_name: greenpath_web
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=greenpath

volumes:
  mysql_data: